version: 1.0.{build}
build:
  verbosity: minimal

artifacts:
  - path: setup.iss 
  
deploy:
- provider: GitHub
  tag: CI-Server-v$(appveyor_build_version)
  release: CI-Server-v$(appveyor_build_version)
  description: Release description
  auth_token:
    secure: r08RY46/Hg/n4nO5iaFpojXXcdhjBkP4fl/KgNqOSAnG8etByXl9h0VeaP1uLiHc
  artifact: setup.iss
  draft: true
  prerelease: false
  on:
    branch: master

